### PR TITLE
012/readme

### LINKED ISSUE #4: Add search closed issues
So developers have that as an additional resource.

### PR DESCRIPTION
**Pull request by payne-chris-r**
Fixes #4 and #5.

### CODE REVIEW

**Comment by gaand** [comment]
Sorry, I thought I responded to this, but apparently not.

Why did you remove the bolding of the steps?

**Comment by payne-chris-r** [comment]
Because the linter yelled at me! ;-)

**Comment by berziiii** [comment]
Due to time constraints, going to merge.

**Comment by jrhorn424** [comment]
Looks good to me. Thanks, Chris.

**Comment by jrhorn424** [comment]
Damn it, @berziiii.

**Comment by jrhorn424** [comment]
I was literally hovering over the button.

**Comment by jrhorn424** [comment]
Any reason we're missing #3 in this PR?

**Comment by payne-chris-r** [comment]
Crap! Not a good one. I wanted to chat with you about it. It's kind of weird to have the "Issue: Closed" at the top. What if we just included https://gist.github.com/Trevoke/3fb5e1c01baa2d6efba7 instead @jrhorn424 ?

**Pull request merged**
